default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: stackshare_demo

test:
  <<: *default
  database: stackshare_demo_test

production:
  <<: *default
  database: stackshare_demo_production
